version: "3.8"
services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8080"

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8080"
    depends_on:
      - user-service
    environment:
      USER_SERVICE_URL: http://user-service:8080
